name: Build on PR or Rebuild Comment
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  issue_comment:
    types: [created]
jobs:
  build:
    if: >
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, 'rebuild'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run build script
        run: |
          cd ./cp2k/2025.1_cuda124.openmpi.skylake-avx512.psmp
          ./build.sh
