name: Build on PR or Rebuild Comment
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  issue_comment:
    types: [created]
jobs:
  build:
    if: >
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, 'rebuild'))
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          swap-storage: false
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run build script
        run: |
          ./cp2k/2025.1-cuda124-openmpi-avx512-psmp/build.sh
